import yaml
from agent.state import AgentState
from app.services.config_utils import validate_config_guards

def run(state: AgentState) -> dict:
    generated_yaml = state.get("generated_yaml")
    
    if not generated_yaml:
        return {
            "validation_result": {"valid": False, "errors": ["No YAML generated by the builder."]},
            "status": "failed",
            "current_node": "yaml_validator"
        }
        
    validation_result = {"valid": True, "errors": [], "warnings": []}
    
    try:
        # Structural check
        yaml.safe_load(generated_yaml)
        
        # Schema/Guard check (assume linux, prod for strictness)
        guard_error = validate_config_guards(generated_yaml, agent_os="linux", env="prod")
        if guard_error:
            validation_result["valid"] = False
            validation_result["errors"].append(guard_error)
            
    except yaml.YAMLError as e:
        validation_result["valid"] = False
        validation_result["errors"].append(f"YAML Syntax Error: {str(e)}")
        
    if not validation_result["valid"]:
        return {
            "validation_result": validation_result,
            "status": "failed",
            "current_node": "yaml_validator",
            "execution_log": [f"[Validator] Validation failed: {validation_result['errors']}"]
        }
        
    # Generate human_review_payload since graph interrupts BEFORE human_review node
    parsed_intent = state.get("parsed_intent", {})
    fleet_name = state.get("fleet_name") or parsed_intent.get("fleet_name", "Unknown Fleet")
    fleet_id = state.get("fleet_id", "New")
    config_profile = parsed_intent.get("config_profile", "custom")
    disabled_metrics = parsed_intent.get("disabled_metrics", [])
    target_agents = parsed_intent.get("target_agents", [])
    
    targets = [{"name": agent, "status": "online"} for agent in target_agents]
    
    yaml_preview_lines = generated_yaml.splitlines()[:20]
    yaml_preview = "\n".join(yaml_preview_lines) + ("\n..." if len(yaml_preview_lines) == 20 else "")

    human_review_payload = {
        "title": "Review before rollout",
        "fleet": {"name": fleet_name, "id": fleet_id, "new": parsed_intent.get("requires_new_fleet", False)},
        "config": {
            "version": state.get("config_version", "v1.0.0"),
            "profile": config_profile,
            "disabled": disabled_metrics,
            "yaml_preview": yaml_preview,
        },
        "targets": targets,
        "warnings": [], 
        "estimated_duration": f"~{max(1, len(target_agents) * 1.5)} seconds",
        "confirmation_required": True,
    }

    return {
        "validation_result": validation_result,
        "human_review_payload": human_review_payload,
        "status": "awaiting_human",
        "current_node": "yaml_validator",
        "execution_log": ["[Validator] YAML structure and schema validated successfully. Awaiting human review."]
    }
